### PR TITLE
Path prefix

### PR DESCRIPTION
**Pull request by julianrubisch**
This PR adds the possibility to specify a file prefix (like `app/models`) via a Churn::ChurnOptions attribute.

### CODE REVIEW

**Comment by danmayer** [comment]
hey sorry I have been a bit busy lately with a new baby... thanks for the PRs, I will pick these up and the other outstanding PR and get the CI box running again in the next few days.

**Comment by julianrubisch** [comment]
Sorry just saw that those two PRs got mixed together. I‘m currently developing another churn/complexity gem, so those PRs would be very welcome. 

And congrats!

**Comment by danmayer** [comment]
merged into master

**Comment by danmayer** [comment]
ok @julianrubisch your changes were merged in and released as 1.0.4 I will have to spend some time to remove a bunch of dependencies and un-needed code that isn't really a runtime dependency, but that will take a bit more work and perhaps I will clean up some interfaces and make that a 2.0.0 in the next few weeks. Let me know if you need anything else.

**Comment by julianrubisch** [comment]
Sweet! Thanks

**Pull request closed without merging**
