### PR TITLE
Fix/filter changes may return nil

### PR DESCRIPTION
**Pull request by julianrubisch**
Sorry, first PR was messed up...

Just noticed I intruduced a bug in `filter_changes` myself by using `select!`, which may return `nil`. Don't know how that could have slipped in, very sorry.

Would be grateful if you could merge this soon :-)

### CODE REVIEW

**Comment by julianrubisch** [comment]
Oh... those CI failures sure _are_ weird...

**Comment by danmayer** [comment]
looking at CI issues

**Comment by danmayer** [comment]
hmm CI seems to now fail on master just with the readme change... thinking something underlying changed on travis ci... They pass locally, so for now merging and will investigate the CI issues later.

Do you need this published as a new version or can you point to the git repo for the gem for now?

**Comment by julianrubisch** [comment]
Hmm... well it does lead to some problems here at the moment, though only sparsely. I think it couldn’t harm releasing a new version if you can spend the time...

**Comment by danmayer** [comment]
Ok i will try to release later today. In Hawaii with the fam at the moment so a bit slow to respond ;)

**Comment by julianrubisch** [comment]
Oh it’s not that urgent, really!

**Comment by danmayer** [comment]
no worries just released pkg/churn-1.0.5.gem to rubygems I am on baby duty and the baby decided it was nap time

**Comment by danmayer** [comment]
resolved CI test issues

**Comment by julianrubisch** [comment]
works like a charm, thanks!

**Pull request merged**
